import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import NextAuthProvider from '@/auth/NextAuthProvider';
import NavBar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'random-miam',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`inter.className`}>
        <NextAuthProvider>
          <div className="w-10/12 m-auto text-center bg-white flex flex-col min-h-screen">
            <NavBar />
            <div className="grow">{children}</div>
            <div>Footer</div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
